sudo: required

services:
  - docker

language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  # Deploy a snapshot version only for master branch and jdk8
  - if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then 
      make;
      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        mvn -s settings.xml deploy -DskipTests;
      fi;
    else
      make linux64 && mvn test;
    fi
